version: "3"

services:
  momca:
    image: momca
    build:
      context: .
      args:
        BACKUP_TRIGGER: ${BACKUP_TRIGGER:-0 0 4 * * ?}
        CACHE_SIZE: ${CACHE_SIZE:-256}
        COLLECTION_CACHE: ${COLLECTION_CACHE:-256}
        HTTPS_PORT: ${HTTPS_PORT:-8443}
        HTTP_PORT: ${HTTP_PORT:-8181}
        INIT_MEMORY: ${INIT_MEMORY:-256}
        LUCENE_BUFFER: ${LUCENE_BUFFER:-256}
        MAIL_DOMAIN: ${MAIL_DOMAIN}
        MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
        MAIL_PASSWORD: ${MAIL_PASSWORD}
        MAIL_USER: ${MAIL_USER}
        MAX_MEMORY: ${MAX_MEMORY:-2048}
        PASSWORD: ${PASSWORD}
        SERVER_NAME: ${SERVER_NAME:-localhost}
        SMTP_URL: ${SMTP_URL}
        USE_SSL: ${USE_SSL:-false}
    environment:
        HTTP_PORT: ${HTTP_PORT:-8181}
    volumes:
      - data:/opt/momca/mom.XRX-data
      - ./my:/opt/momca/mom.XRX/my
    ports: 
      - "${HTTP_PORT:-8181}:${HTTP_PORT:-8181}"
      - "${HTTPS_PORT:-8443}:${HTTPS_PORT:-8443}"
    container_name: momca
    restart: always
    networks:
      - default

volumes:
  data: {}

networks:
  default:
